# Generated by Django 4.2.14 on 2024-08-24 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_address_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('torso', models.FloatField()),
                ('chest', models.FloatField()),
                ('waist', models.FloatField()),
                ('neck', models.FloatField()),
                ('sleeve', models.FloatField()),
                ('inseam', models.FloatField()),
                ('hip', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
