# Generated by Django 4.2.14 on 2024-08-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customermeasurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermeasurements',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customermeasurements',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='chest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='hip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='inseam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='neck',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='sleeve',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='torso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermeasurements',
            name='waist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
