# Generated by Django 4.2.14 on 2024-08-25 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customermeasurements_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermeasurements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermeasurements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
